#!/bin/bash

if [ $# -eq 0 ]
then
	echo "Usage: phone searchfor [... searchfor]"
	echo "(You didn't tell me what you want to search for.)"
	exit 0
fi

list=$1
for name in $@
do
	list=$list'|'$name
done
egrep -i "$list" mydata | awk -f display.awk

