#!/bin/bash
if [ $# -eq 0 ]
then
	echo "Usage: phone searchfor [... searchfor]"
	echo "(You didn't tell me what you want to search for.)"
	exit 0
fi

egrep -i "$1" mydata | egrep -i "$2" | awk -f display.awk


