FR = open('L_In.txt', 'r')
FW = open('L_Out.txt', 'w')

index = FR.readline()
index = int(list(index)[0])
A = FR.readline()
B = FR.readline()
A = list(int(x) for x in A.split())
B = list(int(x) for x in B.split())
print('index =', index, file=FW)
print('A =', A, file=FW)
print('B =', B, file=FW)
print('A[2] + B[2] =', A[2] + B[2], file=FW)
FR.close()
FW.close()